### ISSUE TITLE
When I double click the macosifttcontrol in the app folder no has file is created on desktop

### ISSUE THREAD

**Issue by markperka** [abdyfranco/macos-ifttt-control#12]
I'm trying to install. When i double click the app in the applications folder there is no has file created on the desktop. Any suggestions? It worked the first time i did it, but subsequent installs were needed and since the file has not been created. I've tried my best to deinstall the control using deinstallers, but still no go.

**Comment by abdyfranco** [comment]
This problem is related to #10, which is already in progress.
