### ISSUE TITLE
Installation process continuously loops

### ISSUE THREAD

**Issue by wabiloo** [abdyfranco/macos-ifttt-control#7]
**Describe the bug:**
When I try to install the tool, I get the screen asking me to move the generated file to Dropbox (maOSIFTTTControl subfolder) and provide the public link to it. I do so, and briefly I see new options (to create Webhook etc) but then immediately, the same screen comes back again. I move the file, create the public link, paste it, and the same repeats ad infinitum...

**System Information:**
 - macOS Version: 10.14.3
 - macOS IFTTT Version: ?
 - Involved Applet (link to IFTTT): ?

**Additional context**
*Add any other context about the problem here.*

**Comment by abdyfranco** [comment]
Are you using the latest version of macOS IFTTT Control? You can check the Releases tab in order to download the latest version of macOS IFTTT Control.

**Comment by wabiloo** [comment]
Yes, I was using v1.1.3. I also tried v1.1.2 - same behaviour

**Comment by abdyfranco** [comment]
I released a new update (v1.1.4), please try with this new version if the issue still happening.

**Comment by wabiloo** [comment]
This time it installed. I now just need to go through the rest of the config

**Comment by abdyfranco** [comment]
So... it’s working? :D
